const express = require('express')
const TaskHandler = require('../router_handler/task')
const router = express.Router()
router.get('/pjtitle/:no',TaskHandler.getProjectTitle)
router.get('/pjtitle1/:username',TaskHandler.getProjectTitle1)
router.get('/pooltitle/:no', TaskHandler.getPoolTitle)
router.get('/carditem/:pno', TaskHandler.getCardItem)
router.post('/addcard', TaskHandler.addCardItem)
router.get('/maxindex/:pno',TaskHandler.getMaxIndex)
router.put('/updatecarditem1/:pno/:oldIndex/:newIndex',TaskHandler.updateItemSort)
router.put('/updatecarditem2/:pno/:oldIndex/:newIndex',TaskHandler.updateItemSort1)
router.put('/updatecarditem3/:pno/:oldIndex/:newIndex',TaskHandler.updateItemSort2)
router.put('/updatecarditem4/:oldId/:newId/:oldIndex/:newIndex', TaskHandler.updateItemSort3)
router.put('/updatecarditem5/:oldId/:newId/:oldIndex/:newIndex', TaskHandler.updateItemSort4)
router.post('/addList', TaskHandler.addPoolList)
router.get('/poolMaxId/:no',TaskHandler.getPoolListMaxId)
router.put('/editfinish/:c_item_id/:is_finish', TaskHandler.editFinishState)
module.exports = router
