const express = require('express')
const TaskHandler = require('../router_handler/task')
const router = express.Router()
router.get('/allproject/:username', TaskHandler.getAllProjectTitle)
router.get('/pooltitle/:no', TaskHandler.getPoolTitle)
router.get('/carditem/:pno', TaskHandler.getCardItem)
router.post('/addcard', TaskHandler.addCardItem)
router.get('/maxindex/:pno',TaskHandler.getMaxIndex)
router.put('/updatecarditem1/:pno/:oldIndex/:newIndex',TaskHandler.updateItemSort)
router.put('/updatecarditem2/:pno/:oldIndex/:newIndex',TaskHandler.updateItemSort1)
router.put('/updatecarditem3/:pno/:oldIndex/:newIndex',TaskHandler.updateItemSort2)
router.put('/updatecarditem4/:oldId/:newId/:oldIndex/:newIndex', TaskHandler.updateItemSort3)
router.put('/updatecarditem5/:oldId/:newId/:oldIndex/:newIndex', TaskHandler.updateItemSort4)
router.put('/updatecarditem6/:oldId/:newId/:oldIndex/:newIndex', TaskHandler.updateItemSort5)
router.post('/addList', TaskHandler.addPoolList)
router.get('/poolMaxId/:no',TaskHandler.getPoolListMaxId)
router.put('/editfinish/:c_item_id/:is_finish', TaskHandler.editFinishState)
router.get('/projectMaxNo/:username', TaskHandler.getMaxNo)
router.post('/addprojects', TaskHandler.addProject)
router.post('/collection/:no/:iscol', TaskHandler.editCollection)
router.post('/title/:pname/:no', TaskHandler.editProjectTitle)
router.delete('/project/:username/:no/:pname/:date', TaskHandler.deleteProject)
router.get('/pno/:id', TaskHandler.getCardPno)
router.delete('/card/:pno/:index', TaskHandler.delCardItem)
router.delete('/pool/:pno/:index/:no', TaskHandler.delPoolItem)
router.post('/pool/exchange/:no/:oldIndex/:newIndex', TaskHandler.updatePool1)
router.post('/pool/exchange2/:no/:oldIndex/:newIndex', TaskHandler.updatePool2)
router.post('/pool/exchange3/:no/:oldIndex/:newIndex', TaskHandler.updatePool3)
module.exports = router
